<a href="https://colab.research.google.com/github/wjdgoruds2/AI-_assignment/blob/master/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

data=['cold','cold','warm','cold','hot','hot','warn','cold','warm','hot']
values=array(data)

label_encoder=LabelEncoder()
integer_encoded=label_encoder.fit_transform(values)
print('\n정수 인코딩 \n',integer_encoded)

onehot_encoder=OneHotEncoder(sparse=False)
integer_encoded=integer_encoded.reshape(len(integer_encoded),1)
onehot_encoded=onehot_encoder.fit_transform(integer_encoded)
print('\none-hot 인코딩\n',onehot_encoded)

inverted=label_encoder.inverse_transform([argmax(onehot_encoded[0,:])])
print('\n',onehot_encoded[0],'=>',inverted)



정수 인코딩 
 [0 0 2 0 1 1 3 0 2 1]

one-hot 인코딩
 [[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]

 [1. 0. 0. 0.] => ['cold']


In [ ]:
sle