<a href="https://colab.research.google.com/github/wjdgoruds2/AI-_assignment/blob/master/generation%20algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy

def cal_pop_fitness(equation_inputs,pop):
  fitness=numpy.sum(pop*equation_inputs,axis=1)
  return fitness

def select_mating_pool(pop,fitness,num_parents):
  parents=numpy.empty((num_parents,pop.shape[1]))
  for parent_num in range(num_parents):
    max_fitness_idx=numpy.where(fitness==numpy.max(fitness))
    max_fitness_idx=max_fitness_idx[0][0]
    parents[parent_num, :]=pop[max_fitness_idx, :]
    fitness[max_fitness_idx]=-99999999
  return parents

def crossover(parents,offspring_size):
  offspring=numpy.empty(offspring_size)
  crossover_point=numpy.uint8(numpy.random.randint(1,offspring_size[1]-1))

  for k in range(offspring_size[0]):
    parent1_idx=k%parents.shape[0]
    parent2_idx=(k+1)%parents.shape[0]
    offspring[k,0:crossover_point]=parents[parent1_idx,0:crossover_point]
    offspring[k,crossover_point:]=parents[parent2_idx,crossover_point:]
  return offspring

def mutation(offspring_crossover):
  m_ptr=numpy.uint8(numpy.random.randint(0,offspring_crossover.shape[1]-1))
  for idx in range(offspring_crossover.shape[0]):
    random_value=numpy.random.uniform(-1.0, 1.0, 1)
    offspring_crossover[idx,m_ptr]=offspring_crossover[idx,m_ptr]+random_value
  return offspring_crossover

equation_inputs=[4, -1, 3.1, 4, -6, -4.5]
num_weights=6

sol_per_pop=8
num_parents_mating=4

pop_size=(sol_per_pop,num_weights)
new_population=numpy.random.uniform(low=-4.0,high=4.0,size=pop_size)
print(new_population)

num_generations=10
for generation in range(num_generations):
  fitness=cal_pop_fitness(equation_inputs,new_population)
  parents=select_mating_pool(new_population,fitness,num_parents_mating)
  offspring_crossover=crossover(parents,offspring_size=(pop_size[0]-parents.shape[0],num_weights))
  offspring_mutation=mutation(offspring_crossover)

  new_population[0:parents.shape[0],:]=parents
  new_population[parents.shape[0]:,:]=offspring_mutation

  print("세대:",generation,"=>  best 해:",numpy.max(numpy.sum(new_population*equation_inputs,axis=1)))

fitness=cal_pop_fitness(equation_inputs,new_population)
best_match_idx=numpy.where(fitness==numpy.max(fitness))

print("최적해:",new_population[best_match_idx,:])
print("최적해의 적합도:",fitness[best_match_idx])

[[-3.0224764   3.54809465  0.3632315  -2.74293201  2.29089799  3.89184803]
 [ 0.28405549 -2.24751879  3.32802578  1.48124576 -1.44053687 -3.64231341]
 [ 2.45751947 -3.63102908 -1.87335686  0.86383675 -3.16727763  0.82929911]
 [ 0.2831034  -0.25705704 -1.14818171  3.43931839  0.20170011  1.94875352]
 [ 0.32059846  1.40992514 -0.18672042 -1.0573136  -0.24125196  3.21436497]
 [-3.86713742  1.24225873 -0.45043841  3.35764227 -1.09512818  0.35870593]
 [-2.41117813 -0.67702051 -1.87196618 -3.06557797  1.93202224  1.55730078]
 [ 0.66871538 -3.25074246 -3.80942322 -0.90189254  2.14893366 -3.59726606]]
세대: 0 =>  best 해: 44.659235277104294
세대: 1 =>  best 해: 47.137702061072076
세대: 2 =>  best 해: 49.00583975916919
세대: 3 =>  best 해: 49.00583975916919
세대: 4 =>  best 해: 49.00583975916919
세대: 5 =>  best 해: 51.10685485895219
세대: 6 =>  best 해: 55.517070257768914
세대: 7 =>  best 해: 55.85127680987631
세대: 8 =>  best 해: 57.201010573924705
세대: 9 =>  best 해: 59.57259018402292
최적해: [[[ 0.28405549 -2.65542259  4.